package com.user.model;

import com.user.model.base.BaseAuthInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AuthInfo extends BaseAuthInfo<AuthInfo> {
    public static final AuthInfo dao = new AuthInfo().dao();
}
