package com.user.model;

import com.user.model.base.BaseDataRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataRecord extends BaseDataRecord<DataRecord> {
	public static final DataRecord dao = new DataRecord().dao();
}
