package com.user.model;

import com.user.model.base.BaseGoodsInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsInfo extends BaseGoodsInfo<GoodsInfo> {
	public static final GoodsInfo dao = new GoodsInfo().dao();
}
