package com.user.model;

import com.user.model.base.BaseOrderInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderInfo extends BaseOrderInfo<OrderInfo> {
	public static final OrderInfo dao = new OrderInfo().dao();
}
