package com.user.model;

import com.user.model.base.BaseOrderDetailInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderDetailInfo extends BaseOrderDetailInfo<OrderDetailInfo> {
    public static final OrderDetailInfo dao = new OrderDetailInfo().dao();
}
