package com.user.model;

import com.user.model.base.BasePlayerInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlayerInfo extends BasePlayerInfo<PlayerInfo> {
	public static final PlayerInfo dao = new PlayerInfo().dao();
}
