package com.user.model;

import com.user.model.base.BaseRoleUserInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleUserInfo extends BaseRoleUserInfo<RoleUserInfo> {
    public static final RoleUserInfo dao = new RoleUserInfo().dao();
}
