package com.user.model;

import com.user.model.base.BaseRoleAuthInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleAuthInfo extends BaseRoleAuthInfo<RoleAuthInfo> {
	public static final RoleAuthInfo dao = new RoleAuthInfo().dao();
}
