package com.user.model;

import com.user.model.base.BaseRoleInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleInfo extends BaseRoleInfo<RoleInfo> {
    public static final RoleInfo dao = new RoleInfo().dao();
}
