package com.app.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserInfo<M extends BaseUserInfo<M>> extends Model<M> implements IBean {

    public java.lang.Long getId() {
        return getLong("id");
    }

    public M setId(java.lang.Long id) {
        set("id", id);
        return (M) this;
    }

    public java.lang.String getAccount() {
        return getStr("account");
    }

    public M setAccount(java.lang.String account) {
        set("account", account);
        return (M) this;
    }

    public java.lang.String getPwd() {
        return getStr("pwd");
    }

    public M setPwd(java.lang.String pwd) {
        set("pwd", pwd);
        return (M) this;
    }

    public java.lang.Integer getState() {
        return getInt("state");
    }

    public M setState(java.lang.Integer state) {
        set("state", state);
        return (M) this;
    }

}
