package com.user.model;

import com.user.model.base.BaseUserInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserInfo extends BaseUserInfo<UserInfo> {
    public static final UserInfo dao = new UserInfo().dao();
}
