#server:
#  port: 8082
#  ssl:
#    key-store: keystore.p12
#    key-store-type: PKCS12
#    key-store-password: 123456

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_photo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
      servlet:
        multipart:
          max-request-size: 10MB
          max-file-size: 10MB

mybatis:
  mapper-locations: classpath:mapperxml/*.xml,classpath*:/mapperxml/generate/*.xml

#httpUrl: https://www.gantxlf.cn

logging:
#  level.*: info,debug,error,warn
  level:
    com.photo.mapper: debug